title: Snap! Reference Manual
description: reference manual
theme: just-the-docs
layout: default

url: https://jedi-force.github.io/snap-manual/

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
